### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by kassioribeiro** [konduto/php-sdk#4]
boa noite!
Estou tentando setar o Payment para o objeto Order. No entanto, está sendo retornado para sempre a seguinte mensagem: "send orderArray ( [status] => error [message] => stdClass Object ( [where] => /payment [why] => stdClass Object ( [expected] => Array ( [0] => array ) [found] => object ) ) ) "

Estou setando um array no método setPayment da Order. Segue o código:

`$orderKonduto = new Models\Order();`
`$paymentKonduto = array(`
`"type" => Models\Payment::TYPE_CREDIT,`
 `"bin" => substr($payment["credit_card_number"], 0, 6), // 6 primeiros digitos do cartao de credito`
  `"last4" => substr($payment["credit_card_number"], strlen($payment["credit_card_number"]) - 4, strlen($payment["credit_card_number"])),`
 `"expiration_date" => $ed_month.$ed_year`
  `);`
`$orderKonduto->setPayment($paymentKonduto);`

A mensagem diz que estou setando um objeto, mas estou setando um array mesmo.

**Comment by adri0** [comment]
Olá @kassioribeiro. Para consertar o erro você deve colocar a variável `$paymentKonduto` dentro de outro array. Assim:

``` php
$payment = array($paymentKonduto);
$orderKonduto->setPayment($payment);
```

 O método `setPayment` aceita somente um array cujos elementos são meios de pagamentos. O array que você definiu representa 1 meio de pagamento (poderia ter mais de 1). 

No php quando um _associative array_ é [convertido para json](http://php.net/manual/pt_BR/function.json-encode.php) ele vira um objeto, por isso a mensagem que você está vendo diz que o campo `payment` só aceita array.
