### ISSUE TITLE
Order toJsonArray not returning some elements.

### ISSUE THREAD

**Issue by ishyevandro** [konduto/php-sdk#7]
There's a possible error in Order.php model.

When the returned object from request call "toJsonArray" data of score, recomendation and device are lost in conversion.

**Comment by adri0** [comment]
This is actually not a bug. Currently, the method `toJsonArray` is designed to build the object that will be converted to json required by the API. 

On the other hand, some users might profit from another method that produces an associative array with all the information in the model. I will leave this issue open as a reminder of improvement to future releases.
